# Generated by Django 4.0.3 on 2022-04-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_arquivo_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='arquivo',
            field=models.FileField(null=True, upload_to='referencias'),
        ),
    ]
